Added docstrings in the function_ordering.py
unifyai/lint-hook pull request #6
Opened 2023-11-04 14:10 UTC by he11owthere

2023-11-04 18:11 UTC, NripeshN approved these changes

2023-11-06 10:03 UTC, KareemMAX requested changes
Hey @he11owthere,

Great work, but sadly we are using [numpy docstring style](https://numpydoc.readthedocs.io/en/latest/format.html). Can you refactor your code to match with that?

Also, [according to our docstring deepdive](https://unify.ai/docs/ivy/overview/deep_dive/docstrings.html) you will need to also remove parameter types in favor of using in-code parameter hints.

Also make sure you lint your code before requesting a review

2023-11-20 15:22 UTC, KareemMAX approved these changes

2023-11-20 15:23 UTC, KareemMAX commented
LGTM! I'll leave it for @NripeshN to merge

2023-11-21 20:29 UTC, merged